version: "2"

services:
  app:
    build: .
    container_name: <nome_do_bot>
    command: python -u ./scheduller.py
    restart: unless-stopped
    networks:
      network1:
    volumes:
      - /app/output:/var/docker_volumes/<nome_do_bot>/output
      - /app/logs:/var/docker_volumes/<nome_do_bot>/logs
    environment:
      PYTHONUNBUFFERED: 1
      MODE: PRD

networks:
  network1:
      external:
        name: network1
